name = "VertexSafeGraphs"
uuid = "19fa3120-7c27-5ec5-8db8-b0b0aa330d6f"
authors = ["Mathieu Besançon <mathieu.besancon@gmail.com>"]
version = "0.1.2"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
julia = "1"
Graphs = "1.4"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
